version: '3'

services:
  app:
    build: .
    container_name: rin_kokonoe
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=sqlite:/data/rin_kokonoe.db
      - RUST_LOG=info
      - RSS_OUTPUT_DIR=/rss
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - API_PORT=8080
    volumes:
      - ./data:/data
      - ./rss:/rss
    ports:
      - "8080:8080"
