name: Debug Workflow

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable tmate debugging session'
        required: false
        default: false
        type: boolean

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: List Environment
      run: |
        echo "Rust version:"
        rustc --version
        echo "Cargo version:"
        cargo --version
        echo "Directory structure:"
        ls -la
        echo "Environment variables:"
        env | sort
    
    - name: Build Project
      uses: actions-rs/cargo@v1
      with:
        command: build
    
    - name: Setup tmate session
      if: ${{ inputs.debug_enabled }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
